// Shared DB row/entity types for the main-process persistence layer.
// Non-secret application data only. Credentials are referenced by a
// secure-store key (credential_ref), never stored here.

export type ProviderType = string

export interface ProviderRow {
  id: string
  type: ProviderType
  display_name: string
  enabled: boolean
  base_url: string | null
  created_at: string
  updated_at: string
}

export interface AccountRow {
  id: string
  provider_id: string
  display_name: string
  credential_ref: string
  status: string
  created_at: string
  updated_at: string
}

export interface ModelRow {
  id: string
  provider_id: string
  provider_model_id: string
  display_name: string
  context_window: number | null
  input_price: number | null
  output_price: number | null
  capabilities_json: string | null
  enabled: boolean
  discovered_at: string
}

export interface GatewayConfigRow {
  id: number
  host: string
  port: number
  auth_enabled: boolean
  startup_enabled: boolean
}

// Insert inputs. `id` and timestamps are generated by the repository; other
// optional fields default in the repository (e.g. enabled => true).
export type NewProvider = {
  id?: string
  type: string
  display_name: string
  enabled?: boolean
  base_url?: string | null
}

export type NewAccount = {
  id?: string
  provider_id: string
  display_name: string
  credential_ref: string
  status?: string
}

export type NewModel = {
  id?: string
  provider_id: string
  provider_model_id: string
  display_name: string
  context_window?: number | null
  input_price?: number | null
  output_price?: number | null
  capabilities_json?: string | null
  enabled?: boolean
}

export type NewGatewayConfig = Omit<GatewayConfigRow, 'id'>
