// Shared DB row/entity types for the main-process persistence layer.
// Non-secret application data only. Credentials are referenced by a
// secure-store key (credential_ref), never stored here.

export type ProviderType = string

export interface ProviderRow {
  id: string
  type: ProviderType
  display_name: string
  enabled: boolean
  base_url: string | null
  created_at: string
  updated_at: string
}

export interface AccountRow {
  id: string
  provider_id: string
  display_name: string
  credential_ref: string
  status: string
  created_at: string
  updated_at: string
}

export interface ModelRow {
  id: string
  provider_id: string
  provider_model_id: string
  display_name: string
  context_window: number | null
  input_price: number | null
  output_price: number | null
  capabilities_json: string | null
  enabled: boolean
  discovered_at: string
}

export interface GatewayConfigRow {
  id: number
  host: string
  port: number
  auth_enabled: boolean
  startup_enabled: boolean
}

// Insert inputs. `id` and timestamps are generated by the repository; other
// optional fields default in the repository (e.g. enabled => true).
export type NewProvider = {
  id?: string
  type: string
  display_name: string
  enabled?: boolean
  base_url?: string | null
}

export type NewAccount = {
  id?: string
  provider_id: string
  display_name: string
  credential_ref: string
  status?: string
}

export type NewModel = {
  id?: string
  provider_id: string
  provider_model_id: string
  display_name: string
  context_window?: number | null
  input_price?: number | null
  output_price?: number | null
  capabilities_json?: string | null
  enabled?: boolean
}

export type NewGatewayConfig = Omit<GatewayConfigRow, 'id'>

export interface VirtualModelRow {
  id: string
  display_name: string
  provider_id: string
  provider_model_id: string
  routing_policy_id: string | null
  enabled: boolean
  created_at: string
  updated_at: string
}

export type NewVirtualModel = {
  id?: string
  display_name: string
  provider_id: string
  provider_model_id: string
  routing_policy_id?: string | null
  enabled?: boolean
}

export interface RequestUsageRow {
  id: string
  request_id: string
  virtual_model_id: string
  provider_id: string
  provider_model_id: string
  input_tokens: number
  output_tokens: number
  cached_tokens: number
  estimated_cost: number | null
  latency_ms: number
  status: string
  error_code: string | null
  created_at: string
}

export type NewRequestUsage = Omit<RequestUsageRow, 'id' | 'created_at' | 'estimated_cost'> & {
  id?: string
  created_at?: string
  estimated_cost?: number | null
}
